version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - microservices_network
  service-discovery-container:
    image: samuelgutierrez24/service-discovery-ecommerce-boot:lastest
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-configcontainer:9296/
    networks:
      - microservices_network
  cloud-config-container:
    image: samuelgutierrez24/cloud-config-ecommerce-boot:lastest
    build:
      context: ./cloud-config
      dockerfile: Dockerfile
    ports:
      - 9296:9296
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
    networks:
      - microservices_network
networks:
  microservices_network:
    driver: bridge
