apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-cluster-reader
rules:
- apiGroups: [""] # Core API group
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"] # For deployments
  resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-cluster-reader-binding
subjects:
- kind: ServiceAccount
  name: jenkins # Name of the ServiceAccount used by Jenkins
  namespace: jenkins # Namespace where Jenkins ServiceAccount resides
roleRef:
  kind: ClusterRole
  name: jenkins-cluster-reader
  apiGroup: rbac.authorization.k8s.io