apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: default
---
# Role in the 'default' namespace granting necessary permissions for Jenkins
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default # This Role is for the 'default' namespace
  name: jenkins-default-manager 
rules:
- apiGroups: ["", "apps", "extensions"] # "" is for core resources like pods, services. "apps" for deployments, statefulsets.
  resources: 
    - pods
    - services
    - deployments
    - replicasets
    - statefulsets
    - configmaps
    - secrets
    - persistentvolumeclaims
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "apply"]
- apiGroups: [""] # Core API group
  resources: ["pods/log"] # Permission to get logs from pods
  verbs: ["get", "list", "watch"]
---
# Bind the 'jenkins-default-manager' Role in the 'default' namespace
# to the 'jenkins' ServiceAccount in the 'jenkins' namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-default-manager-binding
  namespace: default # This RoleBinding is in the 'default' namespace
subjects:
- kind: ServiceAccount
  name: jenkins      # The ServiceAccount name used by your Jenkins deployment
  namespace: jenkins  # The namespace where your Jenkins ServiceAccount resides
roleRef:
  kind: Role
  name: jenkins-default-manager # The Role created above
  apiGroup: rbac.authorization.k8s.io