apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: jenkins
---
# Role in the 'jenkins' namespace granting necessary permissions for Jenkins
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jenkins # Changed from default to jenkins
  name: jenkins-manager # Renamed for clarity, was jenkins-deployer
rules:
- apiGroups: [""] # Core API group
  resources: ["services", "pods", "pods/log", "configmaps", "secrets", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# Bind the 'jenkins-manager' Role in the 'jenkins' namespace
# to the 'jenkins' ServiceAccount in the 'jenkins' namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-manager-binding # Renamed for clarity
  namespace: jenkins # Changed from default to jenkins
subjects:
- kind: ServiceAccount
  name: jenkins       # Service Account name used by Jenkins pods
  namespace: jenkins   # Namespace of the Jenkins Service Account
roleRef:
  kind: Role
  name: jenkins-manager # Must match the Role name above
  apiGroup: rbac.authorization.k8s.io