---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  namespace: ecommerce-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
      - name: shipping-service
        image: samuelgutierrez24/shipping-service-ecommerce-boot:lastest
        ports:
        - containerPort: 8600
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://zipkin:9411"
        - name: EUREKA_CLIENT_REGION
          value: "default"
        - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
          value: "myzone"
        - name: EUREKA_CLIENT_SERVICEURL_MYZONE
          value: "http://service-discovery:8761/eureka"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery:8761/eureka/"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://cloud-config:9296/"
        - name: EUREKA_INSTANCE
          value: "shipping-service"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /shipping-service/actuator/health
            port: 8600
          initialDelaySeconds: 120
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /shipping-service/actuator/health
            port: 8600
          initialDelaySeconds: 90
          periodSeconds: 10
      initContainers:
      - name: wait-for-eureka
        image: busybox:1.35
        command: ['sh', '-c']
        args:
          - >
            until nc -z service-discovery 8761;
            do echo waiting for eureka;
            sleep 2;
            done;
      - name: wait-for-config
        image: busybox:1.35
        command: ['sh', '-c']
        args:
          - >
            until nc -z cloud-config 9296;
            do echo waiting for config server;
            sleep 2;
            done;
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: ecommerce-microservices
spec:
  selector:
    app: shipping-service
  ports:
    - port: 8600
      targetPort: 8600
      nodePort: 30600
  type: NodePort
